export const mdFiles = [
  { id: 0, title: "Execution", file: "01. Execution.md" },
  { id: 1, title: "Engines", file: "02. Engines.md" },
  { id: 2, title: "Parsing", file: "03. Parsing.md" },
  { id: 3, title: "Host Environments", file: "04. Host Environments.md" },
  { id: 4, title: "Agents", file: "05. Agents.md" },
  { id: 5, title: "Stack Data Structure", file: "06. Stack Data Structure.md" },
  { id: 6, title: "Heap Of Objects", file: "07. Heap Of Objects.md" },
  { id: 7, title: "Queue Of Jobs", file: "08. Queue Of Jobs.md" },
  { id: 8, title: "Queue Data Structure", file: "09. Queue Data Structure.md" },
  { id: 9, title: "The Event Loop", file: "10. The Event Loop.md" },
  { id: 10, title: "Stack of Execution Contexts", file: "11. Stack of Execution Contexts.md" },
  { id: 11, title: "The Call Stack Example", file: "12. The Call Stack Example.js" },
  { id: 12, title: "Single Threaded", file: "13. Single Threaded.md" },
  { id: 13, title: "Bonus: Stacks In JS", file: "14. Bonus Stacks In JS.js" },
  { id: 14, title: "Compilation And Interpretation", file: "15. Compilation And Interpretation.md" },
  { id: 15, title: "Programming Language Hierarchy", file: "16. Programming Language Hierarchy.md" },
  { id: 16, title: "Computer Memory", file: "17. Computer Memory.md" },
  { id: 17, title: "CPU Registers", file: "18. CPU Registers.md" },
  { id: 18, title: "Memory Addressing", file: "19. Memory Addressing.md" },
];
