export const mdFiles = [
  { id: 0, title: "Database As A Computer", file: "01. Database As A Computer.md" },
  { id: 1, title: "Database As A Concept", file: "02. Database As A Concept.md" },
  { id: 2, title: "Persistent Storage", file: "03. Persistent Storage.md" },
  { id: 3, title: "Computers - DB vs Server vs Client", file: "04. Computers - DB vs Server vs Client.md" },
  { id: 4, title: "Roles - DB vs Server vs Client", file: "05. Roles - DB vs Server vs Client.md" },
  { id: 5, title: "Types Of Databases", file: "06. Types Of Databases.md" },
  { id: 6, title: "Server - Database Connections", file: "07. Server - Database Connections.md" },
  { id: 7, title: "More About Connections", file: "08. More About Connections.md" },
  { id: 8, title: "SQL", file: "09. SQL.md" },
  { id: 9, title: "SQL Categories", file: "10. SQL Categories.md" },
  { id: 10, title: "SQL Syntax", file: "11. SQL Syntax.md" },
  { id: 11, title: "RDBMS", file: "12. RDBMS.md" },
  { id: 12, title: "SQL Keys", file: "13. SQL Keys.md" },
  { id: 13, title: "SQL Relationships", file: "14. SQL Relationships.md" },
  { id: 14, title: "SQL Schemas", file: "15. SQL Schemas.md" },
  { id: 15, title: "MQL", file: "16. MQL.md" },
  { id: 16, title: "MQL Categories", file: "17. MQL Categories.md" },
  { id: 17, title: "MQL Syntax", file: "18. MQL Syntax.md" },
  { id: 18, title: "SQL vs MQL", file: "19. SQL vs MQL.md" },
  { id: 19, title: "MongoDB", file: "20. MongoDB.md" },
  { id: 20, title: "NoSQL Keys", file: "21. NoSQL Keys.md" },
  { id: 21, title: "NoSQL Relationships", file: "22. NoSQL Relationships.md" },
  { id: 22, title: "NoSQL Schemas", file: "23. NoSQL Schemas.md" },
  { id: 23, title: "Storing", file: "24. Storing.md" },
  { id: 24, title: "Retrieval", file: "25. Retrieval.md" },
  { id: 25, title: "Queries", file: "26. Queries.md" },
  { id: 26, title: "Query, Filter, Sort, Select, Limit, Skip", file: "27. Query Filter Sort Select Limit Skip.md" },
  { id: 27, title: "Indexing Data", file: "28. Indexing Data.md" },
  { id: 28, title: "Data Sanitation Review", file: "29. Data Sanitation Review.md" },
  { id: 29, title: "Data Validation Review", file: "30. Data Validation Review.md" },
  { id: 30, title: "Data Constraints", file: "31. Data Constraints.md" },
  { id: 31, title: "Migrations", file: "32. Migrations.md" },
  { id: 32, title: "Migration Files", file: "33. Migration Files.md" },
  { id: 33, title: "Transactions", file: "34. Transactions.md" },
  { id: 34, title: "ORMs and ODMs", file: "35. ORMs and ODMs.md" },
  { id: 35, title: "Models", file: "36. Models.md" },
  { id: 36, title: "Loading", file: "37. Loading.md" },
  { id: 37, title: "Lazy Loading", file: "38. Lazy Loading.md" },
  { id: 38, title: "Eager Loading", file: "39. Eager Loading.md" },
];
