export const sections = [
  {
    id: "databases",
    title: "Databases",
    folder: "databases",
    files: [
      "01. Database As A Computer.md",
      "02. Database As A Concept.md",
      "03. Persistent Storage.md",
      "04. Computers - DB vs Server vs Client.md",
      "05. Roles - DB vs Server vs Client.md",
      "06. Types Of Databases.md",
      "07. Server - Database Connections.md",
      "08. More About Connections.md",
      "09. SQL.md",
      "10. SQL Categories.md",
      "11. SQL Syntax.md",
      "12. RDBMS.md",
      "13. SQL Keys.md",
      "14. SQL Relationships.md",
      "15. SQL Schemas.md",
      "16. MQL.md",
      "17. MQL Categories.md",
      "18. MQL Syntax.md",
      "19. SQL vs MQL.md",
      "20. MongoDB.md",
      "21. NoSQL Keys.md",
      "22. NoSQL Relationships.md",
      "23. NoSQL Schemas.md",
      "24. Storing.md",
      "25. Retrieval.md",
      "26. Queries.md",
      "27. Query Filter Sort Select Limit Skip.md",
      "28. Indexing Data.md",
      "29. Data Sanitation Review.md",
      "30. Data Validation Review.md",
      "31. Data Constraints.md",
      "32. Migrations.md",
      "33. Migration Files.md",
      "34. Transactions.md",
      "35. ORMs and ODMs.md",
      "36. Models.md",
      "37. Loading.md",
      "38. Lazy Loading.md",
      "39. Eager Loading.md",
    ]
  },
  {
    id: "mongoose",
    title: "Mongoose",
    folder: "mongoose",
    files: [
      "01. MongoDB Ecosystem.md",
      "02. MongoDB Terminology.md",
      "03. BSON.md",
      "04. MongoDB Drivers and API.md",
      "05. MongoDB vs Mongoose.md",
      "06. MongoDB Connection Methods.md",
      "07. Atlas Connection Parameters.md",
      "08. URL Query and Request Parameters.md",
      "09. Query Filter Sort Select Limit Skip.md",
      "10. MongoDB Query API.md",
      "11. MongoDB Query Predicates.md",
      "12. Query vs Search.md",
      "13. MongoDB Aggregate Pipeline.md",
      "14. URI Sort Parameter.md",
      "15. URI Sort Builtin vs Custom.md",
      "16. Query Building Pattern.md",
      "17. Numeric Filtering Considerations.md",
      "18. Pagination.md",
      "19. Regular Expressions.md",
      "20. Regex in MongoDB.md",
      "21. Regex Explanation.md",
      "22. String Replace Explanation.md",
      "23. Thenables in Mongoose.md",
      "24. Unhandled Mongoose Promise Query.md",
      "25. Error Objects Review.md",
      "26. JS Error Object.md",
      "27. Express Error Object.md",
      "28. MongoDB Error Object.md",
      "29. Error Handling.md",
      "30. Mongo Walkthrough: Establish Git.md",
      "31. Mongo Walkthrough: Create .env File.md",
      "32. Mongo Walkthrough: Create README.md",
      "33. Mongo Walkthrough: Create Folder Structure.md",
      "34. Mongo Walkthrough: Create Database ERD.md",
      "35. Mongo Walkthrough: Initiate Node.md",
      "36. Mongo Walkthrough: Add Scripts.md",
      "37. Mongo Walkthrough: Create connect.js.md",
      "38. Mongo Walkthrough: Create startServer.js.md",
      "39. Mongo Walkthrough: Create server.js.md",
      "40. Mongo Walkthrough: Test DB Connection.md",
    ]
  },
  {
    id: "prisma",
    title: "Prisma",
    folder: "prisma",
    files: [
      "01. Prisma Overview.md",
      "02. PostgreSQL Ecosystem.md",
      "03. PostgreSQL Terminology.md",
      "04. Prisma vs Raw SQL.md",
      "05. Connection Methods.md",
      "06. Connection Parameters.md",
      "07. Prisma Workflow.md",
      "08. Prisma Schema.md",
      "09. Prisma Schema and Database Schema.md",
      "10. Prisma Migrate.md",
      "11. Prisma Client and Studio.md",
      "12. Prisma Query API.md",
      "13. Prisma Query Operators.md",
      "14. Query Filter Sort Select Limit Skip.md",
      "15. Query Building Pattern.md",
      "16. Relations in Depth.md",
      "17. Eager Loading and Relations.md",
      "18. Aggregation and GroupBy.md",
      "19. Database Transactions.md",
      "20. Batch Operations.md",
      "21. Raw SQL with queryRaw.md",
      "22. Performance Optimization.md",
      "23. Seeding.md",
      "24. Error Handling with Prisma.md",
      "25. Prisma Error Codes.md",
      "26. Advanced Error Handling.md",
      "27. Neon.md",
    ]
  },
];
