export const mdFiles = [
  { id: 0, title: "Rendering Methods", file: "00. Rendering Methods.md" },
  { id: 1, title: "What Is The DOM?", file: "01. What Is The DOM?.md" },
  { id: 2, title: "The Russian Doll", file: "02. The Russian Doll.md" },
  { id: 3, title: "DOM Manipulation", file: "03. DOM Manipulation.md" },
  { id: 4, title: "HTML to JS Mappings", file: "04. HTML to JS Mappings.md" },
  { id: 5, title: "Rendering vs Loading", file: "05. Rendering vs Loading.md" },
  { id: 6, title: "Back In The Day", file: "06. Back In The Day.md" },
  { id: 7, title: "What Is HTML?", file: "07. What Is HTML?.md" },
  { id: 8, title: "Why JS?", file: "08. Why JS?.md" },
  { id: 9, title: "Stupid Circle", file: "09. Stupid Circle.md" },
  { id: 10, title: "Why Still HTML?", file: "10. Why Still HTML?.md" },
  { id: 11, title: "Alternatives", file: "11. Alternatives.md" },
  { id: 12, title: "What Is WASM And WASI", file: "12. What Is WASM And WASI.md" },
  { id: 13, title: "DoOver", file: "13. DoOver.md" },
  { id: 14, title: "Works In Progress", file: "14. Works In Progress.md" },
  { id: 15, title: "WTF CSS?", file: "15. WTF CSS?.md" },
  { id: 16, title: "What Is An API?", file: "16. What Is An API?.md" },
  { id: 17, title: "Why Not Revolution?", file: "17. Why Not Revolution?.md" },
];
