export const mdFiles = [
  { id: 0, title: "Frameworks", file: "00. Frameworks.md" },
  { id: 1, title: "What Is Middleware?", file: "01.a What Is Middleware?.md" },
  { id: 2, title: "Why Is It Called Middleware?", file: "01.aa Why Is It Called Middleware?.md" },
  { id: 3, title: "How Is Middlware Used?", file: "01.aaa How Is Middlware Used?.md" },
  { id: 4, title: "Middleware Ways To Apply", file: "01.b Middleware Ways To Apply.md" },
  { id: 5, title: "Middleware Inline Definition", file: "01.c Middleware Inline Definition.md" },
  { id: 6, title: "Middleware Separtely Defined", file: "01.d Middleware Separtely Defined.md" },
  { id: 7, title: "Middleware Parentheses Or Not", file: "01.e Middleware Parentheses Or Not.md" },
  { id: 8, title: "Other Ways For Middleware", file: "01.f Other Ways For Middleware.md" },
  { id: 9, title: "Routes", file: "02. Routes.md" },
  { id: 10, title: "Handlers", file: "03. Handlers.md" },
  { id: 11, title: "Controllers", file: "04. Controllers.md" },
  { id: 12, title: "Routers", file: "05. Routers.md" },
  { id: 13, title: "Secrets", file: "06. Secrets.md" },
  { id: 14, title: "Logging", file: "07. Logging.md" },
  { id: 15, title: "Documentation", file: "08. Documentation.md" },
  { id: 16, title: "Other Utilities", file: "09. Other Utilities.md" },
];
