export const mdFiles = [
  { id: 0, title: "Accessibility", file: "00. Accessibility.md" },
  { id: 1, title: "Authentication", file: "01. Authentication.md" },
  { id: 2, title: "Session", file: "02. Session.md" },
  { id: 3, title: "SessionServerSideStorage", file: "02. SessionServerSideStorage.md" },
  { id: 4, title: "BrowserStorage", file: "03. BrowserStorage.md" },
  { id: 5, title: "CookieBasedAuthentication", file: "04. CookieBasedAuthentication.md" },
  { id: 6, title: "Cookies", file: "05. Cookies.md" },
  { id: 7, title: "SessionExpiration", file: "06. SessionExpiration.md" },
  { id: 8, title: "PassportIntro", file: "07. PassportIntro.md" },
  { id: 9, title: "LocalStrategy", file: "08. LocalStrategy.md" },
  { id: 10, title: "PassportLifeCycle", file: "09. PassportLifeCycle.md" },
  { id: 11, title: "SerializeDeserialize", file: "10. SerializeDeserialize.md" },
  { id: 12, title: "PasswordHashing", file: "11. PasswordHashing.md" },
  { id: 13, title: "ProtectedRoutes", file: "12. ProtectedRoutes.md" },
  { id: 14, title: "ErrorHandling", file: "13. ErrorHandling.md" },
  { id: 15, title: "OtherStrategies", file: "14. OtherStrategies.md" },
  { id: 16, title: "CompleteExample", file: "15. CompleteExample.md" },
  { id: 17, title: "CommonIssues", file: "16. CommonIssues.md" },
  { id: 18, title: "SecurityChecklist", file: "17. SecurityChecklist.md" },
];
