export const mdFiles = [
  { id: 0, title: "MongoDB Ecosystem", file: "01. MongoDB Ecosystem.md" },
  { id: 1, title: "MongoDB Terminology", file: "02. MongoDB Terminology.md" },
  { id: 2, title: "BSON", file: "03. BSON.md" },
  { id: 3, title: "MongoDB Drivers and API", file: "04. MongoDB Drivers and API.md" },
  { id: 4, title: "MongoDB vs Mongoose", file: "05. MongoDB vs Mongoose.md" },
  { id: 5, title: "MongoDB Connection Methods", file: "06. MongoDB Connection Methods.md" },
  { id: 6, title: "Atlas Connection Parameters", file: "07. Atlas Connection Parameters.md" },
  { id: 7, title: "URL Query and Request Parameters", file: "08. URL Query and Request Parameters.md" },
  { id: 8, title: "Query Filter Sort Select Limit Skip", file: "09. Query Filter Sort Select Limit Skip.md" },
  { id: 9, title: "MongoDB Query API", file: "10. MongoDB Query API.md" },
  { id: 10, title: "MongoDB Query Predicates", file: "11. MongoDB Query Predicates.md" },
  { id: 11, title: "Query vs Search", file: "12. Query vs Search.md" },
  { id: 12, title: "MongoDB Aggregate Pipeline", file: "13. MongoDB Aggregate Pipeline.md" },
  { id: 13, title: "URI Sort Parameter", file: "14. URI Sort Parameter.md" },
  { id: 14, title: "URI Sort Builtin vs Custom", file: "15. URI Sort Builtin vs Custom.md" },
  { id: 15, title: "Query Building Pattern", file: "16. Query Building Pattern.md" },
  { id: 16, title: "Numeric Filtering Considerations", file: "17. Numeric Filtering Considerations.md" },
  { id: 17, title: "Pagination", file: "18. Pagination.md" },
  { id: 18, title: "Regular Expressions", file: "19. Regular Expressions.md" },
  { id: 19, title: "Regex in MongoDB", file: "20. Regex in MongoDB.md" },
  { id: 20, title: "Regex Explanation", file: "21. Regex Explanation.md" },
  { id: 21, title: "String Replace Explanation", file: "22. String Replace Explanation.md" },
  { id: 22, title: "Thenables in Mongoose", file: "23. Thenables in Mongoose.md" },
  { id: 23, title: "Unhandled Mongoose Promise Query", file: "24. Unhandled Mongoose Promise Query.md" },
  { id: 24, title: "Error Objects Review", file: "25. Error Objects Review.md" },
  { id: 25, title: "JS Error Object", file: "26. JS Error Object.md" },
  { id: 26, title: "Express Error Object", file: "27. Express Error Object.md" },
  { id: 27, title: "MongoDB Error Object", file: "28. MongoDB Error Object.md" },
  { id: 28, title: "Error Handling", file: "29. Error Handling.md" },
  { id: 29, title: "Walkthrough: Establish Git", file: "30. Mongo Walkthrough: Establish Git.md" },
  { id: 30, title: "Walkthrough: Create .env File", file: "31. Mongo Walkthrough: Create .env File.md" },
  { id: 31, title: "Walkthrough: Create README", file: "32. Mongo Walkthrough: Create README.md" },
  { id: 32, title: "Walkthrough: Create Folder Structure", file: "33. Mongo Walkthrough: Create Folder Structure.md" },
  { id: 33, title: "Walkthrough: Create Database ERD", file: "34. Mongo Walkthrough: Create Database ERD.md" },
  { id: 34, title: "Walkthrough: Initiate Node", file: "35. Mongo Walkthrough: Initiate Node.md" },
  { id: 35, title: "Walkthrough: Add Scripts", file: "36. Mongo Walkthrough: Add Scripts.md" },
  { id: 36, title: "Walkthrough: Create connect.js", file: "37. Mongo Walkthrough: Create connect.js.md" },
  { id: 37, title: "Walkthrough: Create startServer.js", file: "38. Mongo Walkthrough: Create startServer.js.md" },
  { id: 38, title: "Walkthrough: Create server.js", file: "39. Mongo Walkthrough: Create server.js.md" },
  { id: 39, title: "Walkthrough: Test DB Connection", file: "40. Mongo Walkthrough: Test DB Connection.md" },
];
