export const mdFiles = [
  { id: 0, title: "Summary of Authentication Tools", file: "_SummaryOfAuthenticationTools.md" },
  { id: 1, title: "Authentication Vs Authorization", file: "01. Authentication Vs Authorization.md" },
  { id: 2, title: "Authentication Security Summary", file: "02. Authentication Security Summary.md" },
  { id: 3, title: "Stateless", file: "03. Stateless.md" },
  { id: 4, title: "TCP Stateful", file: "04. TCPStateful.md" },
  { id: 5, title: "JSON Web Token", file: "05. jsonwebtoken.md" },
  { id: 6, title: "JSON Web Token Package", file: "06. jsonwebtokenPackage.md" },
  { id: 7, title: "Random Key Generator", file: "07. Random Key Generator.md" },
  { id: 8, title: "Base64URL Encode", file: "08. Base64URLEncode.md" },
  { id: 9, title: "Hashing", file: "09. Hashing.md" },
  { id: 10, title: "Cryptography", file: "10. Cryptography.md" },
  { id: 11, title: "Encryption", file: "11. Encryption.md" },
  { id: 12, title: "HTTPS", file: "12. HTTPS.md" },
  { id: 13, title: "Browser Storage", file: "13. BrowserStorage.md" },
  { id: 14, title: "Cookies", file: "14. cookies.md" },
  { id: 15, title: "HTTP Only Cookie", file: "15. HTTPOnlyCookie.md" },
  { id: 16, title: "JWT Base64URL", file: "16. JWT Base64URL.md" },
  { id: 17, title: "Closer Look Base64URL Encoded", file: "17. CloserLookBase64URLEncoded.md" },
  { id: 18, title: "JWT Header", file: "18. JWTHeader.md" },
  { id: 19, title: "JWT Payload", file: "19. JWTPayload.md" },
  { id: 20, title: "JWT Signature", file: "20. JWTSignature.md" },
  { id: 21, title: "JWT Example", file: "21. JWTExample.md" },
  { id: 22, title: "HTTP Status Codes", file: "22. httpstatuscodes.md" }
];
