export const mdFiles = [
  { id: 0, title: "Security Levels", file: "00. Security Levels.md" },
  { id: 1, title: "OSI Layers", file: "01. OSI Layers.md" },
  { id: 2, title: "Security Terminology", file: "01. Security Terminology.md" },
  { id: 3, title: "Security Headers", file: "02. Security Headers.md" },
  { id: 4, title: "Authorization", file: "03. Authorization.md" },
  { id: 5, title: "Authentication", file: "04. Authentication.md" },
  { id: 6, title: "Cookies", file: "05. Cookies.md" },
  { id: 7, title: "JWT vid-notes", file: "06. JWT vid-notes.md" },
  { id: 8, title: "Intro to Web Application Security", file: "07. Intro to Web Application Security.md" },
  { id: 9, title: "What is a Csrf Attack?", file: "08. What is a Csrf Attack?.md" },
  { id: 10, title: "How to Prevent Csrf Attacks in Express", file: "09. How to Prevent Csrf Attacks in Express.md" },
  { id: 11, title: "What is Cors?", file: "10. What is Cors?.md" },
  { id: 12, title: "Cors in Express", file: "11. Cors in Express.md" },
  { id: 13, title: "What is Xss?", file: "12. What is Xss?.md" },
  { id: 14, title: "What is Jwt?", file: "13. What is Jwt?.md" },
  { id: 15, title: "Jwt in Javascript", file: "14. Jwt in Javascript.md" },
  { id: 16, title: "Roles and Permissions", file: "15. Roles and Permissions.md" },
  { id: 17, title: "Scoping Model Attributes", file: "16. Scoping Model Attributes.md" },
  { id: 18, title: "Hashing Passwords", file: "17. Hashing Passwords.md" },
  { id: 19, title: "What is a Rainbow Table Attack?", file: "18. What is a Rainbow Table Attack?.md" },
  { id: 20, title: "Salt Passwords Before Hashing", file: "19. Salt Passwords Before Hashing.md" },
  { id: 21, title: "Prevent Hashed Password Leaks", file: "20. Prevent Hashed Password Leaks.md" },
  { id: 22, title: "Bcrypt", file: "21. Bcrypt.md" },
];
