export const mdFiles = [
  { id: 0, title: "Node HTTP Basics", file: "00. Node HTTP Basics.md" },
  { id: 1, title: "RESTful Routes", file: "00. RESTful Routes.md" },
  { id: 2, title: "Servers", file: "00. Servers.md" },
  { id: 3, title: "HTTP Request Response", file: "01. HTTP Request Response.md" },
  { id: 4, title: "HTTP and HTTPS", file: "01. HTTP and HTTPS.md" },
  { id: 5, title: "Servers and APIs", file: "01. Servers and APIs.md" },
  { id: 6, title: "HTTP Protocol", file: "02. HTTP Protocol.md" },
  { id: 7, title: "Route Handlers and Static Assets", file: "02. Route Handlers and Static Assets.md" },
  { id: 8, title: "The Request Response Cycle", file: "02. The Request Response Cycle.md" },
  { id: 9, title: "Express Setup", file: "03. Express Setup.md" },
  { id: 10, title: "HTTP Request", file: "03. HTTP Request.md" },
  { id: 11, title: "The Request Response Objects", file: "03. The Request Response Objects.md" },
  { id: 12, title: "Express Routes and Middleware", file: "04. Express Routes and Middleware.md" },
  { id: 13, title: "HTTP Methods", file: "04. HTTP Methods.md" },
  { id: 14, title: "HTTP Response", file: "04. HTTP Response.md" },
  { id: 15, title: "Database Architecture Patterns", file: "05. Database Architecture Patterns.md" },
  { id: 16, title: "Enpoints", file: "05. Enpoints.md" },
  { id: 17, title: "HTTP Form Submission", file: "05. HTTP Form Submission.md" },
  { id: 18, title: "REST API", file: "06. REST API.md" },
  { id: 19, title: "Schema Setup", file: "06. Schema Setup.md" },
  { id: 20, title: "NODE HTTP & EXPRESS", file: "NODE HTTP & EXPRESS.md" },
  { id: 21, title: "REST and the Req Res Cycle", file: "REST and the Req Res Cycle.md" },
];
