import { sections } from "./sections";

function findTopics(ids) {
  return sections.filter(s => ids.includes(s.id));
}

export const subjects = [
  {
    id: "01-intro-to-computer-science",
    title: "01. Intro To Computer Science",
    courses: [
      { id: "00-what-is-a-signal", title: "00. What Is A Signal", topics: findTopics(["00-what-is-a-signal"]) },
      { id: "01-what-is-electricity", title: "01. What Is Electricity", topics: findTopics(["01-what-is-electricity"]) },
      { id: "02-what-is-a-circuit", title: "02. What Is A Circuit", topics: findTopics(["02-what-is-a-circuit"]) },
      { id: "03-circuit-components", title: "03. Circuit Components", topics: findTopics(["03-circuit-components"]) },
      { id: "04-logic-gates", title: "04. Logic Gates", topics: findTopics(["04-logic-gates"]) },
      { id: "05-transistors", title: "05. Transistors", topics: findTopics(["05-transistors"]) },
      { id: "06-integrated-circuits", title: "06. Integrated Circuits", topics: findTopics(["06-integrated-circuits"]) },
      { id: "07-what-is-a-computer", title: "07. What Is A Computer", topics: findTopics(["07-what-is-a-computer"]) },
      { id: "08-how-the-web-works", title: "08. How The Web Works", topics: findTopics(["08-how-the-web-works"]) },
      { id: "09-more-about-networks", title: "09. More About Networks", topics: findTopics(["09-more-about-networks"]) },
    ],
  },
  {
    id: "02-information-technology",
    title: "02. Information Technology",
    courses: [
    ],
  },
  {
    id: "03-networking",
    title: "03. Networking",
    courses: [
    ],
  },
  {
    id: "04-operating-systems",
    title: "04. Operating Systems",
    courses: [
      { id: "00-components-of-an-os", title: "00. Components Of An OS", topics: findTopics(["00-components-of-an-os"]) },
      { id: "00-unix", title: "00. Unix", topics: findTopics(["00-unix"]) },
      { id: "01-linux", title: "01. Linux", topics: findTopics(["01-linux"]) },
      { id: "02-mac-os", title: "02. Mac OS", topics: findTopics(["02-mac-os"]) },
      { id: "03-windows", title: "03. Windows", topics: findTopics(["03-windows"]) },
      { id: "04-ios", title: "04. iOS", topics: findTopics(["04-ios"]) },
      { id: "05-android", title: "05. Android", topics: findTopics(["05-android"]) },
      { id: "06-chromium", title: "06. Chromium", topics: findTopics(["06-chromium"]) },
      { id: "07-graphene", title: "07. Graphene", topics: findTopics(["07-graphene"]) },
    ],
  },
  {
    id: "05-programing-languages",
    title: "05. Programing Languages",
    courses: [
      { id: "strongly-typed-languages", title: "Strongly Typed Languages", topics: findTopics(["strongly-typed-languages"]) },
      { id: "weakly-typed-languages", title: "Weakly Typed Languages", topics: findTopics(["weakly-typed-languages"]) },
    ],
  },
  {
    id: "06-shell-grep-git-github-gh-cli-md",
    title: "06. Shell, Grep, Git, GitHub, GH CLI.md",
    courses: [
      { id: "01-shell", title: "01. Shell", topics: findTopics(["01-shell"]) },
      { id: "02-grep", title: "02. Grep", topics: findTopics(["02-grep"]) },
      { id: "03-git", title: "03. Git", topics: findTopics(["03-git"]) },
      { id: "04-github-cli", title: "04. GitHub CLI", topics: findTopics(["04-github-cli"]) },
    ],
  },
  {
    id: "07-html-and-css",
    title: "07. HTML and CSS",
    courses: [
      { id: "00-html", title: "00. HTML", topics: findTopics(["00-html"]) },
      { id: "01-css", title: "01. CSS", topics: findTopics(["01-css"]) },
      { id: "02-browsers", title: "02. Browsers", topics: findTopics(["02-browsers"]) },
      { id: "03-environments-and-core-utilities", title: "03. Environments and Core Utilities", topics: findTopics(["03-environments-and-core-utilities"]) },
      { id: "04-design-and-accessibility", title: "04. Design and Accessibility", topics: findTopics(["04-design-and-accessibility"]) },
      { id: "05-web-builders", title: "05. Web Builders", topics: findTopics(["05-web-builders"]) },
    ],
  },
  {
    id: "08-browsers",
    title: "08. Browsers",
    courses: [
    ],
  },
  {
    id: "09-javascript",
    title: "09. JavaScript",
    courses: [
      { id: "images", title: "images", topics: findTopics([]) },
      { id: "markdown", title: "markdown", topics: findTopics(["markdown"]) },
    ],
  },
  {
    id: "10-advanced-javascript",
    title: "10. Advanced JavaScript",
    courses: [
      { id: "01-misc-js", title: "01. Misc JS", topics: findTopics(["01-misc-js"]) },
      { id: "02-oop-and-context", title: "02. OOP and Context", topics: findTopics(["02-oop-and-context"]) },
      { id: "03-functions", title: "03. Functions", topics: findTopics(["03-functions"]) },
      { id: "04-callbacks", title: "04. Callbacks", topics: findTopics(["04-callbacks"]) },
      { id: "05-promises", title: "05. Promises", topics: findTopics(["05-promises"]) },
      { id: "06-async-await", title: "06. Async Await", topics: findTopics(["06-async-await"]) },
      { id: "07-recursion", title: "07. Recursion", topics: findTopics(["07-recursion"]) },
      { id: "08-closure", title: "08. Closure", topics: findTopics(["08-closure"]) },
      { id: "09-time-and-space-complexity", title: "09. Time And Space Complexity", topics: findTopics(["09-time-and-space-complexity"]) },
      { id: "10-data-structures", title: "10. Data Structures", topics: findTopics(["10-data-structures"]) },
      { id: "11-algorithms", title: "11. Algorithms", topics: findTopics(["11-algorithms"]) },
      { id: "12-blind75", title: "12. Blind75", topics: findTopics(["blind-75"]) },
    ],
  },
  {
    id: "11-react-redux-and-remix",
    title: "11. React, Redux, and Remix",
    courses: [
    ],
  },
  {
    id: "12-node",
    title: "12. Node",
    courses: [
      { id: "01-node-tools-for-development-part-i", title: "01. Node Tools For Development Part I", topics: findTopics(["01-chrome-browser","02-postman","03-vscode","04-setting-up-chrome-vscode-and-postman","05-chrome-devtools","06-postman-in-action","07-editors-explained"]) },
      { id: "02-node-tools-for-development-part-ii", title: "02. Node Tools For Development Part II", topics: findTopics(["01-shell","02-terminal","03-setting-up-your-shell-and-terminal","04-cli-vs-gui","05-using-applications-with-cli","06-opening-apps-with-cli","02-node-tools-for-development-part-ii-07-interactive-vs-non-interactive","08-running-a-bash-script-file"]) },
      { id: "03-node-tools-for-development-part-iii", title: "03. Node Tools For Development Part III", topics: findTopics(["01-git","02-github","03-github-cli","04-setting-up-git-github-and-github-cli","05-repositories","06-creating-a-local-repo","07-three-areas","08-add-changes","09-commit-changes","10-treeish-commits","10-b-branching","11-creating-a-remote-repo","12-connecting-local-and-remote","13-pushing","15-pulling-to-local","16-pull-requests","17-cloning-a-repo","18-forking-a-repo","19-additional-functionality"]) },
      { id: "04-node-tools-for-development-part-iv", title: "04. Node Tools For Development Part IV", topics: findTopics(["01-cases-and-conventions","02-javascript","03-ecmascript","04-libraries","05-frameworks","06-artificial-intelligence","09-developing-on-thin-clients"]) },
      { id: "05-node-introduction", title: "05. Node Introduction", topics: findTopics(["01-what-is-node","02-node-vs-browser","03-why-node","04-what-is-a-script","05-what-is-a-scripting-language","06-shell-scripts-vs-js-python-scripts","05-node-introduction-07-interactive-vs-non-interactive","07-b-engines","08-programming-language-hierarchy","09-lower-level-language-costs","10-higher-level-language-costs"]) },
      { id: "06-node-version-manager", title: "06. Node Version Manager", topics: findTopics(["01-node-version-manager","02-installing-node-version-manager","03-nvm-commands"]) },
      { id: "07-node-installation", title: "07. Node Installation", topics: findTopics(["01-installing-node-with-nvm","02-installing-node-via-download","03-node-commands"]) },
      { id: "08-node-js-runtime", title: "08. Node JS Runtime", topics: findTopics(["00-what-is-a-runtime-environment","02-using-node-repl","03-using-node-to-run-a-file","04-browser-console","08-node-learning-resources"]) },
      { id: "09-node-architecture", title: "09. Node Architecture", topics: findTopics(["01-engines","02-parsing","03-node-v8-engine","04-agents","05-stack-data-structure","06-heap-of-objects","07-queue-of-jobs","08-queue-data-structure","09-the-event-loop","10-stack-of-execution-contexts","12-single-threaded","14-compilation-and-interpretation"]) },
      { id: "10-node-vs-browsers", title: "10. Node vs Browsers", topics: findTopics(["01-node-vs-browsers","02-general-differences","03-global-objects-differences","04-apis-available","05-async-differences","06-performance-differences","07-module-systems-differences","08-environment-detection","09-use-cases","10-isomorphic-javascript"]) },
      { id: "11-node-jom", title: "11. Node JOM", topics: findTopics(["01-js-objects","02-interacting-with-objects","03-pojo-vs-cijo","04-classes","05-apie","06-nesting","07-jom","08-globalthis","09-this","10-window","11-bom","12-accessing-the-bom","13-nom","14-global","15-scoping","16-global-vs-global-objects"]) },
      { id: "12-node-globals", title: "12. Node Globals", topics: findTopics(["04-globals","05-two-types-of-globals","06-node-globals","07-node-vs-browser","08-the-global-object","09-the-console-object","10-the-process-object","11-secrets-via-process","12-module","13-require","14-dirname","15-filename"]) },
      { id: "13-node-errors", title: "13. Node Errors", topics: findTopics(["00-error-terminology","01-bugs-vs-errors","01-errors-vs-exceptions","02-the-error-object","03-throwing-errors","04-try-catch-finally","05-js-errors-are-blocking","06-js-error-types","07-browser-errors","08-node-errors","09-express-errors","10-custom-errors","11-statuserror"]) },
      { id: "14-node-imports-and-exports", title: "14. Node Imports and Exports", topics: findTopics(["01-what-are-modules","02-what-is-ecma","03-ecmascript-versions","04-js-module-history","05-cjs-vs-esm","06-imports","07-exports","08-type-module"]) },
      { id: "15-node-standard-library", title: "15. Node Standard Library", topics: findTopics(["00-files-modules-packages","01-frameworks-libraries-registry","02-node-standard-library","03-node-standard-library-vs-globals","04-dependencies","05-node-documentation"]) },
      { id: "16-node-os-module", title: "16. Node os Module", topics: findTopics(["16-node-os-module-00-welcome"]) },
      { id: "17-node-path-module", title: "17. Node path Module", topics: findTopics(["01-path-module"]) },
      { id: "18-node-fs-module", title: "18. Node fs Module", topics: findTopics(["18-node-fs-module-00-welcome"]) },
      { id: "19-node-readline-module", title: "19. Node Readline Module", topics: findTopics(["00-readline"]) },
      { id: "20-node-event-loop", title: "20. Node Event Loop", topics: findTopics(["00-control-flow","02-the-call-stack-revisited","03-synchronous-blocking","05-aynchronous-non-blocking","06-the-event-loop","07-the-micro-task-queue","08-callbacks","09-promises","10-fetch","11-async-await","12-async-await-vs-then","13-input-output"]) },
      { id: "21-node-timers-module", title: "21. Node timers Module", topics: findTopics(["05-settimeout","06-setinterval"]) },
      { id: "22-node-event-module", title: "22. Node event Module", topics: findTopics(["01-event-driven-architecture","02-browser-events","03-browser-event-object","04-events-in-the-browser","05-events-in-node","06-browser-vs-node-events","07-on","08-emit","09-simple-eventemitter-example","10-off-vs-removelistener","11-once","12-what-happens-internally","13-why-emitters","14-propogation-delegation-defaults","15-eda-differences"]) },
      { id: "23-node-stream-module", title: "23. Node stream Module", topics: findTopics(["23-node-stream-module-00-welcome"]) },
      { id: "24-node-readline-module", title: "24. Node readline Module", topics: findTopics(["24-node-readline-module-00-welcome"]) },
      { id: "25-node-decoder-module", title: "25. Node decoder Module", topics: findTopics(["25-node-decoder-module-00-welcome"]) },
      { id: "26-node-http-module", title: "26. Node http Module", topics: findTopics(["00-node-http-basics","00-restful-routes","00-servers","01-http-request-response","01-http-and-https","01-servers-and-apis","02-http-protocol","02-route-handlers-and-static-assets","02-the-request-response-cycle","03-express-setup","03-http-request","03-the-request-response-objects","04-express-routes-and-middleware","04-http-methods","04-http-response","05-database-architecture-patterns","05-enpoints","05-http-form-submission","06-rest-api","06-schema-setup","node-http-express","rest-and-the-req-res-cycle"]) },
      { id: "27-node-https-module", title: "27. Node https Module", topics: findTopics(["01-http-package-for-node-copy","02-routes-and-endpoints","03-route-handlers","04-middleware","05-static-assets","06-server-side-vs-client-side-rendering","07-html-templating"]) },
      { id: "28-node-package-manager", title: "28. Node Package Manager", topics: findTopics(["01-node-package-manager","02-node-files-modules-and-packages","03-package-json","04-example-package-json","05-environments","06-commands","07-package-lock-json","08-example-package-lock-json","09-npm-and-built-in-node-modules","10-npmjs-com","11-npx","12-example-module","13-example-package","14-example-package2"]) },
      { id: "29-node-pnpm-package", title: "29. Node pnpm Package", topics: findTopics(["00-what-is-pnpm","01-pnpm-vs-npm-vs-yarn"]) },
      { id: "30-node-yarn-package", title: "30. Node yarn Package", topics: findTopics(["00-what-is-yarn","01-yarn-commands"]) },
      { id: "31-node-express-part-i-server-basics", title: "31. Node Express Part I - Server Basics", topics: findTopics(["01-frameworks","02-what-is-middleware","03-why-is-it-called-middleware","04-how-is-middlware-used","05-middleware-ways-to-apply","06-middleware-inline-definition","07-middleware-separtely-defined","08-middleware-parentheses-or-not","09-other-ways-for-middleware","10-routes","11-handlers","12-controllers","13-routers","14-secrets","15-logging","16-documentation","17-other-utilities"]) },
      { id: "32-node-dotenv-package", title: "32. Node Dotenv Package", topics: findTopics(["32-node-dotenv-package-00-welcome"]) },
      { id: "33-node-nodemon-package", title: "33. Node Nodemon Package", topics: findTopics(["33-node-nodemon-package-00-welcome"]) },
      { id: "34-node-newman-package", title: "34. Node Newman Package", topics: findTopics(["00-fetch","01-fetch-limitations","02-postman-basics","03-postman-collections","04-postman-collaboration"]) },
      { id: "35-node-js-docs-package", title: "35. Node JS Docs Package", topics: findTopics(["35-node-js-docs-package-00-welcome"]) },
      { id: "36-node-winston-package", title: "36. Node Winston Package", topics: findTopics(["36-node-winston-package-00-welcome"]) },
      { id: "37-node-swagger-package", title: "37. Node Swagger Package", topics: findTopics(["openapi","swagger"]) },
      { id: "38-node-express-part-ii-data-integrity", title: "38. Node Express Part II - Data Integrity", topics: findTopics(["00-data-integrity","01-sanitization","02-validation","03-regex-question","04-database-constraints"]) },
      { id: "39-node-joi-package", title: "39. Node Joi Package", topics: findTopics(["39-node-joi-package-00-welcome"]) },
      { id: "40-node-validator-package", title: "40. Node Validator Package", topics: findTopics(["40-node-validator-package-00-welcome"]) },
      { id: "41-node-express-validator-package", title: "41. Node Express-Validator Package", topics: findTopics(["00-what-is-express-validator"]) },
      { id: "42-node-express-part-iii-security", title: "42. Node Express Part III - Security", topics: findTopics(["00-security-levels","01-osi-layers","01-security-terminology","02-security-headers","03-authentication","03-authorization","04-authentication","04-authorization","42-node-express-part-iii-security-05-cookies","06-jwt-vid-notes","07-intro-to-web-application-security","08-what-is-a-csrf-attack","09-how-to-prevent-csrf-attacks-in-express","10-what-is-cors","11-cors-in-express","12-what-is-xss","13-what-is-jwt","14-jwt-in-javascript","15-roles-and-permissions","16-scoping-model-attributes","17-hashing-passwords","18-what-is-a-rainbow-table-attack","19-salt-passwords-before-hashing","20-prevent-hashed-password-leaks","21-bcrypt","security"]) },
      { id: "43-node-helmet-package", title: "43. Node Helmet Package", topics: findTopics(["00-helmet","01-what-is-helmet"]) },
      { id: "44-node-bcrypt-module", title: "44. Node Bcrypt Module", topics: findTopics(["44-node-bcrypt-module-00-welcome"]) },
      { id: "45-node-jsonwebtoken-package", title: "45. Node jsonwebtoken Package", topics: findTopics(["00-summaryofauthenticationtools","01-authentication-vs-authorization","02-authentication-security-summary","03-stateless","04-tcpstateful","05-jsonwebtoken","06-jsonwebtokenpackage","07-random-key-generator","08-base64urlencode","09-hashing","10-cryptography","11-encryption","12-https","13-browserstorage","14-jwt-in-url","14-cookies","15-httponlycookie","16-jwt-base64url","17-closerlookbase64urlencoded","18-jwtheader","19-jwtpayload","20-jwtsignature","21-jwtexample","22-httpstatuscodes","23-stolen-jwt","24-what-is-the-use-of-jwt"]) },
      { id: "46-node-cookie-parser-package", title: "46. Node cookie-parser Package", topics: findTopics(["00-what-is-cookie-parser","01-cookie-options"]) },
      { id: "47-node-express-xss-sanitizer-package", title: "47. Node express-xss-sanitizer Package", topics: findTopics(["00-what-is-express-xss-sanitizer","01-xss-prevention-strategies"]) },
      { id: "48-node-express-rate-limit-package", title: "48. Node express-rate-limit Package", topics: findTopics(["00-what-is-express-rate-limit","01-rate-limiting-strategies"]) },
      { id: "49-node-cors-package", title: "49. Node CORS Package", topics: findTopics(["49-node-cors-package-00-welcome","cors"]) },
      { id: "50-node-passport-package", title: "50. Node Passport Package", topics: findTopics(["00-accessibility","01-authentication","02-session","02-sessionserversidestorage","03-browserstorage","04-cookiebasedauthentication","50-node-passport-package-05-cookies","06-sessionexpiration","07-passportintro","08-localstrategy","09-passportlifecycle","10-serializedeserialize","11-passwordhashing","12-protectedroutes","13-errorhandling","14-otherstrategies","15-completeexample","16-commonissues","17-securitychecklist","changes","readme"]) },
      { id: "51-node-express-part-iv-databases", title: "51. Node Express Part IV - Databases", topics: findTopics(["01-database-as-a-computer","02-database-as-a-concept","03-persistent-storage","04-computers-db-vs-server-vs-client","05-roles-db-vs-server-vs-client","06-types-of-databases","07-server-database-connections","08-more-about-connections","09-sql","10-sql-categories","11-sql-syntax","12-rdbms","13-sql-keys","14-sql-relationships","15-sql-schemas","16-mql","17-mql-categories","18-mql-syntax","19-sql-vs-mql","20-mongodb","21-nosql-keys","22-nosql-relationships","23-nosql-schemas","24-storing","25-retrieval","26-queries","27-query-filter-sort-select-limit-skip","28-indexing-data","29-data-sanitation-review","30-data-validation-review","31-data-constraints","32-migrations","33-migration-files","34-transactions","35-orms-and-odms","36-models","37-loading","38-lazy-loading","39-eager-loading"]) },
      { id: "52-node-express-part-iv-b-rdbms", title: "52. Node Express Part IV.b - RDBMS", topics: findTopics(["01-postgresql","02-mysql","03-sqlite","04-mariadb","05-microsoft-sql-server","06-oracle-database","07-rdbms-comparison"]) },
      { id: "53-node-mongoose-package", title: "53. Node Mongoose Package", topics: findTopics(["01-mongodb-ecosystem","02-mongodb-terminology","03-bson","04-mongodb-drivers-and-api","05-mongodb-vs-mongoose","06-mongodb-connection-methods","07-atlas-connection-parameters","08-url-query-and-request-parameters","09-query-filter-sort-select-limit-skip","10-mongodb-query-api","11-mongodb-query-predicates","12-query-vs-search","13-mongodb-aggregate-pipeline","14-uri-sort-parameter","15-uri-sort-builtin-vs-custom","16-query-building-pattern","17-numeric-filtering-considerations","18-pagination","19-regular-expressions","20-regex-in-mongodb","21-regex-explanation","22-string-replace-explanation","23-thenables-in-mongoose","24-unhandled-mongoose-promise-query","25-error-objects-review","26-js-error-object","27-express-error-object","28-mongodb-error-object","29-error-handling","30-mongo-walkthrough-establish-git","31-mongo-walkthrough-create-env-file","32-mongo-walkthrough-create-readme","33-mongo-walkthrough-create-folder-structure","34-mongo-walkthrough-create-database-erd","35-mongo-walkthrough-initiate-node","36-mongo-walkthrough-add-scripts","37-mongo-walkthrough-create-connect-js","38-mongo-walkthrough-create-startserver-js","39-mongo-walkthrough-create-server-js","40-mongo-walkthrough-test-db-connection"]) },
      { id: "54-node-prisma-package", title: "54. Node Prisma Package", topics: findTopics(["01-prisma-overview","02-postgresql-ecosystem","03-postgresql-terminology","04-prisma-vs-raw-sql","05-connection-methods","06-connection-parameters","07-prisma-workflow","08-prisma-schema","09-prisma-schema-and-database-schema","10-prisma-migrate","11-prisma-client-and-studio","12-prisma-query-api","13-prisma-query-operators","14-query-filter-sort-select-limit-skip","15-query-building-pattern","16-relations-in-depth","17-eager-loading-and-relations","18-aggregation-and-groupby","19-database-transactions","20-batch-operations","21-raw-sql-with-queryraw","22-performance-optimization","23-seeding","24-error-handling-with-prisma","25-prisma-error-codes","26-advanced-error-handling","27-neon"]) },
      { id: "55-node-sequelize-package", title: "55. Node Sequelize Package", topics: findTopics(["01-query-filter-sort-select-limit-skip","sequelize","sql-and-sqlite3"]) },
      { id: "56-node-express-part-v-rendering", title: "56. Node Express Part V - Rendering", topics: findTopics(["00-rendering-methods","01-what-is-the-dom","02-the-russian-doll","03-dom-manipulation","04-html-to-js-mappings","05-rendering-vs-loading","06-back-in-the-day","07-what-is-html","08-why-js","09-stupid-circle","10-why-still-html","11-alternatives","12-what-is-wasm-and-wasi","13-doover","14-works-in-progress","15-wtf-css","16-what-is-an-api","17-why-not-revolution"]) },
      { id: "57-node-ejs-package", title: "57. Node EJS Package", topics: findTopics(["57-node-ejs-package-00-welcome"]) },
      { id: "58-node-react-package", title: "58. Node React Package", topics: findTopics(["58-node-react-package-00-welcome"]) },
      { id: "59-node-express-part-vi-testing", title: "59. Node Express Part VI - Testing", topics: findTopics(["00-errors","00-testing-summary","01-testing","02-benchmarking","03-cypress-testing","tests-and-testing"]) },
      { id: "60-node-jest-package", title: "60. Node Jest Package", topics: findTopics(["60-node-jest-package-00-welcome"]) },
      { id: "61-node-chai-package", title: "61. Node Chai Package", topics: findTopics(["61-node-chai-package-00-welcome"]) },
      { id: "62-node-mocha-package", title: "62. Node Mocha Package", topics: findTopics(["62-node-mocha-package-00-welcome"]) },
      { id: "63-node-xlsx-and-exceljs-packages", title: "63. Node xlsx and exceljs Packages", topics: findTopics(["63-node-xlsx-and-exceljs-packages-00-welcome"]) },
      { id: "64-node-docx-docstemplater-mammoth-packages", title: "64. Node docx docstemplater mammoth Packages", topics: findTopics(["64-node-docx-docstemplater-mammoth-packages-00-welcome"]) },
      { id: "65-node-pptxgenjs-package", title: "65. Node pptxgenjs Package", topics: findTopics(["65-node-pptxgenjs-package-00-welcome"]) },
      { id: "66-node-puppeteer-and-pdf-lib-packages", title: "66. Node puppeteer and pdf-lib Packages", topics: findTopics(["66-node-puppeteer-and-pdf-lib-packages-00-welcome"]) },
      { id: "67-node-nodemailer-package", title: "67. Node Nodemailer Package", topics: findTopics(["67-node-nodemailer-package-00-welcome"]) },
      { id: "68-deployment", title: "68. Deployment", topics: findTopics(["68-deployment-00-welcome"]) },
      { id: "69-architecture", title: "69. Architecture", topics: findTopics(["69-architecture-00-welcome"]) },
      { id: "70-node-lodash-package", title: "70. Node Lodash Package", topics: findTopics(["70-node-lodash-package-00-welcome"]) },
      { id: "71-node-pm2-package", title: "71. Node PM2 Package", topics: findTopics(["71-node-pm2-package-00-welcome"]) },
      { id: "72-node-eslint-package", title: "72. Node ESLint Package", topics: findTopics(["72-node-eslint-package-00-welcome"]) },
      { id: "73-node-vs-bun-runtime", title: "73. Node vs Bun Runtime", topics: findTopics(["73-node-vs-bun-runtime-00-welcome"]) },
      { id: "74-node-vite", title: "74. Node Vite", topics: findTopics(["74-node-vite-00-welcome"]) },
      { id: "75-node-socket-io-package", title: "75. Node Socket.IO Package", topics: findTopics(["75-node-socket-io-package-00-welcome"]) },
      { id: "76-node-moment-package", title: "76. Node Moment Package", topics: findTopics(["76-node-moment-package-00-welcome"]) },
      { id: "77-node-babel-package", title: "77. Node Babel Package", topics: findTopics(["77-node-babel-package-00-welcome"]) },
      { id: "78-node-cloudinary-package", title: "78. Node Cloudinary Package", topics: findTopics(["78-node-cloudinary-package-00-welcome"]) },
      { id: "79-software-development-kits", title: "79. Software Development Kits", topics: findTopics(["79-software-development-kits-00-welcome"]) },
    ],
  },
  {
    id: "13-typescript",
    title: "13. TypeScript",
    courses: [
    ],
  },
  {
    id: "14-rust",
    title: "14. Rust",
    courses: [
      { id: "00-web-assembly", title: "00. Web Assembly", topics: findTopics(["00-web-assembly"]) },
      { id: "01-what-is-rust", title: "01. What Is Rust?", topics: findTopics(["01-what-is-rust"]) },
      { id: "02-rust-basics", title: "02. Rust Basics", topics: findTopics(["02-rust-basics"]) },
      { id: "03-cargo", title: "03. Cargo", topics: findTopics(["03-cargo"]) },
    ],
  },
  {
    id: "15-developer-operations",
    title: "15. Developer Operations",
    courses: [
      { id: "configuration-files", title: "Configuration Files", topics: findTopics(["configuration-files"]) },
      { id: "continuous-development", title: "Continuous Development", topics: findTopics(["continuous-development"]) },
      { id: "continuous-integration", title: "Continuous Integration", topics: findTopics(["continuous-integration"]) },
      { id: "deployment", title: "Deployment", topics: findTopics(["deployment"]) },
    ],
  },
  {
    id: "16-system-design",
    title: "16. System Design",
    courses: [
      { id: "caching", title: "Caching", topics: findTopics(["caching"]) },
      { id: "redis", title: "Redis", topics: findTopics(["redis"]) },
      { id: "kafka", title: "kafka", topics: findTopics(["kafka"]) },
    ],
  },
  {
    id: "17-job-interviewing",
    title: "17. Job Interviewing",
    courses: [
    ],
  },
  {
    id: "18-blockchain",
    title: "18. Blockchain",
    courses: [
    ],
  },
  {
    id: "19-ai",
    title: "19. AI",
    courses: [
    ],
  },
  {
    id: "20-quantum-computing",
    title: "20. Quantum Computing",
    courses: [
    ],
  },
  {
    id: "21-software-learning",
    title: "21. Software Learning",
    courses: [
      { id: "adobe-suite", title: "Adobe Suite", topics: findTopics(["adobe-suite"]) },
      { id: "office-suite", title: "Office Suite", topics: findTopics(["office-suite"]) },
    ],
  },
];
