import { sections } from "./sections";

function findTopics(ids) {
  return sections.filter(s => ids.includes(s.id));
}

export const subjects = [
  {
    id: "01-intro-to-computer-science",
    title: "01. Intro To Computer Science",
    courses: [
      { id: "00-what-is-a-signal", title: "00. What Is A Signal", topics: findTopics(["00-what-is-a-signal"]) },
      { id: "01-what-is-electricity", title: "01. What Is Electricity", topics: findTopics(["01-what-is-electricity"]) },
      { id: "02-what-is-a-circuit", title: "02. What Is A Circuit", topics: findTopics(["02-what-is-a-circuit"]) },
      { id: "03-circuit-components", title: "03. Circuit Components", topics: findTopics(["03-circuit-components"]) },
      { id: "04-logic-gates", title: "04. Logic Gates", topics: findTopics(["04-logic-gates"]) },
      { id: "05-transistors", title: "05. Transistors", topics: findTopics(["05-transistors"]) },
      { id: "06-integrated-circuits", title: "06. Integrated Circuits", topics: findTopics(["06-integrated-circuits"]) },
      { id: "07-what-is-a-computer", title: "07. What Is A Computer", topics: findTopics(["07-what-is-a-computer"]) },
      { id: "08-how-the-web-works", title: "08. How The Web Works", topics: findTopics(["08-how-the-web-works"]) },
      { id: "09-more-about-networks", title: "09. More About Networks", topics: findTopics(["09-more-about-networks"]) },
    ],
  },
  {
    id: "02-information-technology",
    title: "02. Information Technology",
    courses: [
    ],
  },
  {
    id: "03-networking",
    title: "03. Networking",
    courses: [
    ],
  },
  {
    id: "04-operating-systems",
    title: "04. Operating Systems",
    courses: [
      { id: "00-components-of-an-os", title: "00. Components Of An OS", topics: findTopics(["00-components-of-an-os"]) },
      { id: "00-unix", title: "00. Unix", topics: findTopics(["00-unix"]) },
      { id: "01-linux", title: "01. Linux", topics: findTopics(["01-linux"]) },
      { id: "02-mac-os", title: "02. Mac OS", topics: findTopics(["02-mac-os"]) },
      { id: "03-windows", title: "03. Windows", topics: findTopics(["03-windows"]) },
      { id: "04-ios", title: "04. iOS", topics: findTopics(["04-ios"]) },
      { id: "05-android", title: "05. Android", topics: findTopics(["05-android"]) },
      { id: "06-chromium", title: "06. Chromium", topics: findTopics(["06-chromium"]) },
      { id: "07-graphene", title: "07. Graphene", topics: findTopics(["07-graphene"]) },
    ],
  },
  {
    id: "05-programing-languages",
    title: "05. Programing Languages",
    courses: [
      { id: "strongly-typed-languages", title: "Strongly Typed Languages", topics: findTopics(["strongly-typed-languages"]) },
      { id: "weakly-typed-languages", title: "Weakly Typed Languages", topics: findTopics(["weakly-typed-languages"]) },
    ],
  },
  {
    id: "06-shell-grep-git-github-gh-cli-md",
    title: "06. Shell, Grep, Git, GitHub, GH CLI.md",
    courses: [
      { id: "01-shell", title: "01. Shell", topics: findTopics(["01-shell"]) },
      { id: "02-grep", title: "02. Grep", topics: findTopics(["02-grep"]) },
      { id: "03-git", title: "03. Git", topics: findTopics(["03-git"]) },
      { id: "04-github-cli", title: "04. GitHub CLI", topics: findTopics(["04-github-cli"]) },
    ],
  },
  {
    id: "07-html-and-css",
    title: "07. HTML and CSS",
    courses: [
      { id: "00-html", title: "00. HTML", topics: findTopics(["00-html"]) },
      { id: "01-css", title: "01. CSS", topics: findTopics(["01-css"]) },
      { id: "02-browsers", title: "02. Browsers", topics: findTopics(["02-browsers"]) },
      { id: "03-environments-and-core-utilities", title: "03. Environments and Core Utilities", topics: findTopics(["03-environments-and-core-utilities"]) },
      { id: "04-design-and-accessibility", title: "04. Design and Accessibility", topics: findTopics(["04-design-and-accessibility"]) },
      { id: "05-web-builders", title: "05. Web Builders", topics: findTopics(["05-web-builders"]) },
    ],
  },
  {
    id: "08-browsers",
    title: "08. Browsers",
    courses: [
    ],
  },
  {
    id: "09-javascript",
    title: "09. JavaScript",
    courses: [
      { id: "images", title: "images", topics: findTopics([]) },
      { id: "markdown", title: "markdown", topics: findTopics(["markdown"]) },
    ],
  },
  {
    id: "10-advanced-javascript",
    title: "10. Advanced JavaScript",
    courses: [
      { id: "01-misc-js", title: "01. Misc JS", topics: findTopics(["01-misc-js"]) },
      { id: "02-oop-and-context", title: "02. OOP and Context", topics: findTopics(["02-oop-and-context"]) },
      { id: "03-functions", title: "03. Functions", topics: findTopics(["03-functions"]) },
      { id: "04-callbacks", title: "04. Callbacks", topics: findTopics(["04-callbacks"]) },
      { id: "05-promises", title: "05. Promises", topics: findTopics(["05-promises"]) },
      { id: "06-async-await", title: "06. Async Await", topics: findTopics(["06-async-await"]) },
      { id: "07-recursion", title: "07. Recursion", topics: findTopics(["07-recursion"]) },
      { id: "08-closure", title: "08. Closure", topics: findTopics(["08-closure"]) },
      { id: "09-time-and-space-complexity", title: "09. Time And Space Complexity", topics: findTopics(["09-time-and-space-complexity"]) },
      { id: "10-data-structures", title: "10. Data Structures", topics: findTopics(["10-data-structures"]) },
      { id: "11-algorithms", title: "11. Algorithms", topics: findTopics(["11-algorithms"]) },
      { id: "12-blind75", title: "12. Blind75", topics: findTopics(["blind-75"]) },
    ],
  },
  {
    id: "11-react-redux-and-remix",
    title: "11. React, Redux, and Remix",
    courses: [
    ],
  },
  {
    id: "12-node",
    title: "12. Node",
    courses: [
      { id: "01-node-tools-for-development-part-i", title: "01. Node Tools For Development Part I", topics: findTopics(["01-node-tools-for-development-part-i"]) },
      { id: "02-node-tools-for-development-part-ii", title: "02. Node Tools For Development Part II", topics: findTopics(["02-node-tools-for-development-part-ii"]) },
      { id: "03-node-tools-for-development-part-iii", title: "03. Node Tools For Development Part III", topics: findTopics(["03-node-tools-for-development-part-iii"]) },
      { id: "04-node-tools-for-development-part-iv", title: "04. Node Tools For Development Part IV", topics: findTopics(["04-node-tools-for-development-part-iv"]) },
      { id: "05-node-introduction", title: "05. Node Introduction", topics: findTopics(["05-node-introduction"]) },
      { id: "06-node-version-manager", title: "06. Node Version Manager", topics: findTopics(["06-node-version-manager"]) },
      { id: "07-node-installation", title: "07. Node Installation", topics: findTopics(["07-node-installation"]) },
      { id: "08-node-js-runtime", title: "08. Node JS Runtime", topics: findTopics(["08-node-js-runtime"]) },
      { id: "09-node-architecture", title: "09. Node Architecture", topics: findTopics(["09-node-architecture"]) },
      { id: "10-node-vs-browsers", title: "10. Node vs Browsers", topics: findTopics(["10-node-vs-browsers"]) },
      { id: "11-node-jom", title: "11. Node JOM", topics: findTopics(["11-node-jom"]) },
      { id: "12-node-globals", title: "12. Node Globals", topics: findTopics(["12-node-globals"]) },
      { id: "13-node-errors", title: "13. Node Errors", topics: findTopics(["13-node-errors"]) },
      { id: "14-node-imports-and-exports", title: "14. Node Imports and Exports", topics: findTopics(["14-node-imports-and-exports"]) },
      { id: "15-node-standard-library", title: "15. Node Standard Library", topics: findTopics(["15-node-standard-library"]) },
      { id: "16-node-os-module", title: "16. Node os Module", topics: findTopics(["16-node-os-module"]) },
      { id: "17-node-path-module", title: "17. Node path Module", topics: findTopics(["17-node-path-module"]) },
      { id: "18-node-fs-module", title: "18. Node fs Module", topics: findTopics(["18-node-fs-module"]) },
      { id: "19-node-readline-module", title: "19. Node Readline Module", topics: findTopics(["19-node-readline-module"]) },
      { id: "20-node-event-loop", title: "20. Node Event Loop", topics: findTopics(["20-node-event-loop"]) },
      { id: "21-node-timers-module", title: "21. Node timers Module", topics: findTopics(["21-node-timers-module"]) },
      { id: "22-node-event-module", title: "22. Node event Module", topics: findTopics(["22-node-event-module"]) },
      { id: "23-node-stream-module", title: "23. Node stream Module", topics: findTopics(["23-node-stream-module"]) },
      { id: "24-node-readline-module", title: "24. Node readline Module", topics: findTopics(["24-node-readline-module"]) },
      { id: "25-node-decoder-module", title: "25. Node decoder Module", topics: findTopics(["25-node-decoder-module"]) },
      { id: "26-node-http-module", title: "26. Node http Module", topics: findTopics(["26-node-http-module"]) },
      { id: "27-node-https-module", title: "27. Node https Module", topics: findTopics(["27-node-https-module"]) },
      { id: "28-node-package-manager", title: "28. Node Package Manager", topics: findTopics(["28-node-package-manager"]) },
      { id: "29-node-pnpm-package", title: "29. Node pnpm Package", topics: findTopics(["29-node-pnpm-package"]) },
      { id: "30-node-yarn-package", title: "30. Node yarn Package", topics: findTopics(["30-node-yarn-package"]) },
      { id: "31-node-express-part-i-server-basics", title: "31. Node Express Part I - Server Basics", topics: findTopics(["31-node-express-part-i-server-basics"]) },
      { id: "32-node-dotenv-package", title: "32. Node Dotenv Package", topics: findTopics(["32-node-dotenv-package"]) },
      { id: "33-node-nodemon-package", title: "33. Node Nodemon Package", topics: findTopics(["33-node-nodemon-package"]) },
      { id: "34-node-newman-package", title: "34. Node Newman Package", topics: findTopics(["34-node-newman-package"]) },
      { id: "35-node-js-docs-package", title: "35. Node JS Docs Package", topics: findTopics(["35-node-js-docs-package"]) },
      { id: "36-node-winston-package", title: "36. Node Winston Package", topics: findTopics(["36-node-winston-package"]) },
      { id: "37-node-swagger-package", title: "37. Node Swagger Package", topics: findTopics(["37-node-swagger-package"]) },
      { id: "38-node-express-part-ii-data-integrity", title: "38. Node Express Part II - Data Integrity", topics: findTopics(["38-node-express-part-ii-data-integrity"]) },
      { id: "39-node-joi-package", title: "39. Node Joi Package", topics: findTopics(["39-node-joi-package"]) },
      { id: "40-node-validator-package", title: "40. Node Validator Package", topics: findTopics(["40-node-validator-package"]) },
      { id: "41-node-express-validator-package", title: "41. Node Express-Validator Package", topics: findTopics(["41-node-express-validator-package"]) },
      { id: "42-node-express-part-iii-security", title: "42. Node Express Part III - Security", topics: findTopics(["42-node-express-part-iii-security"]) },
      { id: "43-node-helmet-package", title: "43. Node Helmet Package", topics: findTopics(["43-node-helmet-package"]) },
      { id: "44-node-bcrypt-module", title: "44. Node Bcrypt Module", topics: findTopics(["44-node-bcrypt-module"]) },
      { id: "45-node-jsonwebtoken-package", title: "45. Node jsonwebtoken Package", topics: findTopics(["45-node-jsonwebtoken-package"]) },
      { id: "46-node-cookie-parser-package", title: "46. Node cookie-parser Package", topics: findTopics(["46-node-cookie-parser-package"]) },
      { id: "47-node-express-xss-sanitizer-package", title: "47. Node express-xss-sanitizer Package", topics: findTopics(["47-node-express-xss-sanitizer-package"]) },
      { id: "48-node-express-rate-limit-package", title: "48. Node express-rate-limit Package", topics: findTopics(["48-node-express-rate-limit-package"]) },
      { id: "49-node-cors-package", title: "49. Node CORS Package", topics: findTopics(["49-node-cors-package"]) },
      { id: "50-node-passport-package", title: "50. Node Passport Package", topics: findTopics(["50-node-passport-package"]) },
      { id: "51-node-express-part-iv-databases", title: "51. Node Express Part IV - Databases", topics: findTopics(["51-node-express-part-iv-databases"]) },
      { id: "52-node-express-part-iv-b-rdbms", title: "52. Node Express Part IV.b - RDBMS", topics: findTopics(["52-node-express-part-iv-b-rdbms"]) },
      { id: "53-node-mongoose-package", title: "53. Node Mongoose Package", topics: findTopics(["53-node-mongoose-package"]) },
      { id: "54-node-prisma-package", title: "54. Node Prisma Package", topics: findTopics(["54-node-prisma-package"]) },
      { id: "55-node-sequelize-package", title: "55. Node Sequelize Package", topics: findTopics(["55-node-sequelize-package"]) },
      { id: "56-node-express-part-v-rendering", title: "56. Node Express Part V - Rendering", topics: findTopics(["56-node-express-part-v-rendering"]) },
      { id: "57-node-ejs-package", title: "57. Node EJS Package", topics: findTopics(["57-node-ejs-package"]) },
      { id: "58-node-react-package", title: "58. Node React Package", topics: findTopics(["58-node-react-package"]) },
      { id: "59-node-express-part-vi-testing", title: "59. Node Express Part VI - Testing", topics: findTopics(["59-node-express-part-vi-testing"]) },
      { id: "60-node-jest-package", title: "60. Node Jest Package", topics: findTopics(["60-node-jest-package"]) },
      { id: "61-node-chai-package", title: "61. Node Chai Package", topics: findTopics(["61-node-chai-package"]) },
      { id: "62-node-mocha-package", title: "62. Node Mocha Package", topics: findTopics(["62-node-mocha-package"]) },
      { id: "63-node-xlsx-and-exceljs-packages", title: "63. Node xlsx and exceljs Packages", topics: findTopics(["63-node-xlsx-and-exceljs-packages"]) },
      { id: "64-node-docx-docstemplater-mammoth-packages", title: "64. Node docx docstemplater mammoth Packages", topics: findTopics(["64-node-docx-docstemplater-mammoth-packages"]) },
      { id: "65-node-pptxgenjs-package", title: "65. Node pptxgenjs Package", topics: findTopics(["65-node-pptxgenjs-package"]) },
      { id: "66-node-puppeteer-and-pdf-lib-packages", title: "66. Node puppeteer and pdf-lib Packages", topics: findTopics(["66-node-puppeteer-and-pdf-lib-packages"]) },
      { id: "67-node-nodemailer-package", title: "67. Node Nodemailer Package", topics: findTopics(["67-node-nodemailer-package"]) },
      { id: "68-deployment", title: "68. Deployment", topics: findTopics(["68-deployment"]) },
      { id: "69-architecture", title: "69. Architecture", topics: findTopics(["69-architecture"]) },
      { id: "70-node-lodash-package", title: "70. Node Lodash Package", topics: findTopics(["70-node-lodash-package"]) },
      { id: "71-node-pm2-package", title: "71. Node PM2 Package", topics: findTopics(["71-node-pm2-package"]) },
      { id: "72-node-eslint-package", title: "72. Node ESLint Package", topics: findTopics(["72-node-eslint-package"]) },
      { id: "73-node-vs-bun-runtime", title: "73. Node vs Bun Runtime", topics: findTopics(["73-node-vs-bun-runtime"]) },
      { id: "74-node-vite", title: "74. Node Vite", topics: findTopics(["74-node-vite"]) },
      { id: "75-node-socket-io-package", title: "75. Node Socket.IO Package", topics: findTopics(["75-node-socket-io-package"]) },
      { id: "76-node-moment-package", title: "76. Node Moment Package", topics: findTopics(["76-node-moment-package"]) },
      { id: "77-node-babel-package", title: "77. Node Babel Package", topics: findTopics(["77-node-babel-package"]) },
      { id: "78-node-cloudinary-package", title: "78. Node Cloudinary Package", topics: findTopics(["78-node-cloudinary-package"]) },
      { id: "79-software-development-kits", title: "79. Software Development Kits", topics: findTopics(["79-software-development-kits"]) },
    ],
  },
  {
    id: "13-typescript",
    title: "13. TypeScript",
    courses: [
    ],
  },
  {
    id: "14-rust",
    title: "14. Rust",
    courses: [
      { id: "00-web-assembly", title: "00. Web Assembly", topics: findTopics(["00-web-assembly"]) },
      { id: "01-what-is-rust", title: "01. What Is Rust?", topics: findTopics(["01-what-is-rust"]) },
      { id: "02-rust-basics", title: "02. Rust Basics", topics: findTopics(["02-rust-basics"]) },
      { id: "03-cargo", title: "03. Cargo", topics: findTopics(["03-cargo"]) },
    ],
  },
  {
    id: "15-developer-operations",
    title: "15. Developer Operations",
    courses: [
      { id: "configuration-files", title: "Configuration Files", topics: findTopics(["configuration-files"]) },
      { id: "continuous-development", title: "Continuous Development", topics: findTopics(["continuous-development"]) },
      { id: "continuous-integration", title: "Continuous Integration", topics: findTopics(["continuous-integration"]) },
      { id: "deployment", title: "Deployment", topics: findTopics(["deployment"]) },
    ],
  },
  {
    id: "16-system-design",
    title: "16. System Design",
    courses: [
      { id: "caching", title: "Caching", topics: findTopics(["caching"]) },
      { id: "redis", title: "Redis", topics: findTopics(["redis"]) },
      { id: "kafka", title: "kafka", topics: findTopics(["kafka"]) },
    ],
  },
  {
    id: "17-job-interviewing",
    title: "17. Job Interviewing",
    courses: [
    ],
  },
  {
    id: "18-blockchain",
    title: "18. Blockchain",
    courses: [
    ],
  },
  {
    id: "19-ai",
    title: "19. AI",
    courses: [
    ],
  },
  {
    id: "20-quantum-computing",
    title: "20. Quantum Computing",
    courses: [
    ],
  },
  {
    id: "21-software-learning",
    title: "21. Software Learning",
    courses: [
      { id: "adobe-suite", title: "Adobe Suite", topics: findTopics(["adobe-suite"]) },
      { id: "office-suite", title: "Office Suite", topics: findTopics(["office-suite"]) },
    ],
  },
];
