export const mdFiles = [
  { id: 0, title: "Prisma Overview", file: "01. Prisma Overview.md" },
  { id: 1, title: "PostgreSQL Ecosystem", file: "02. PostgreSQL Ecosystem.md" },
  { id: 2, title: "PostgreSQL Terminology", file: "03. PostgreSQL Terminology.md" },
  { id: 3, title: "Prisma vs Raw SQL", file: "04. Prisma vs Raw SQL.md" },
  { id: 4, title: "Connection Methods", file: "05. Connection Methods.md" },
  { id: 5, title: "Connection Parameters", file: "06. Connection Parameters.md" },
  { id: 6, title: "Prisma Workflow", file: "07. Prisma Workflow.md" },
  { id: 7, title: "Prisma Schema", file: "08. Prisma Schema.md" },
  { id: 8, title: "Prisma Schema and Database Schema", file: "09. Prisma Schema and Database Schema.md" },
  { id: 9, title: "Prisma Migrate", file: "10. Prisma Migrate.md" },
  { id: 10, title: "Prisma Client and Studio", file: "11. Prisma Client and Studio.md" },
  { id: 11, title: "Prisma Query API", file: "12. Prisma Query API.md" },
  { id: 12, title: "Prisma Query Operators", file: "13. Prisma Query Operators.md" },
  { id: 13, title: "Query, Filter, Sort, Select, Limit, Skip", file: "14. Query Filter Sort Select Limit Skip.md" },
  { id: 14, title: "Query Building Pattern", file: "15. Query Building Pattern.md" },
  { id: 15, title: "Relations in Depth", file: "16. Relations in Depth.md" },
  { id: 16, title: "Eager Loading and Relations", file: "17. Eager Loading and Relations.md" },
  { id: 17, title: "Aggregation and GroupBy", file: "18. Aggregation and GroupBy.md" },
  { id: 18, title: "Database Transactions", file: "19. Database Transactions.md" },
  { id: 19, title: "Batch Operations", file: "20. Batch Operations.md" },
  { id: 20, title: "Raw SQL with $queryRaw", file: "21. Raw SQL with queryRaw.md" },
  { id: 21, title: "Performance Optimization", file: "22. Performance Optimization.md" },
  { id: 22, title: "Seeding", file: "23. Seeding.md" },
  { id: 23, title: "Error Handling with Prisma", file: "24. Error Handling with Prisma.md" },
  { id: 24, title: "Prisma Error Codes", file: "25. Prisma Error Codes.md" },
  { id: 25, title: "Advanced Error Handling", file: "26. Advanced Error Handling.md" },
  { id: 26, title: "Neon", file: "27. Neon.md" },
];
